module.exports={
    buttonlogin :{
        backgroundColor :'#C29E11',
        color : '#fff',
        padding :10,
        borderRadius: 40,
        fontSize: 32,
        textAlign: 'center',
        minWidth : 300,
        marginTop : 70,
        width: '50%',
        marginLeft: 55,
    },
    buttonsignup :{
        backgroundColor :'#C29E11',
        color : '#fff',
        padding :10,
        borderRadius: 40,
        fontSize: 32,
        textAlign: 'center',
        minWidth : 300,
        marginTop : 10,
        width: '50%',
        marginLeft: 53,
    },
    buttonnSend :{
        backgroundColor :'#C29E11',
        color : 'black',
        padding :10,
        borderRadius: 40,
        fontSize: 32,
        textAlign: 'center',
        marginTop : 60,
        height: 60,
        width: '30%',
        marginLeft: 150,
        fontWeight: "bold",
    }
}